piwik_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: dev
      threads: 4
